In [1]:
# ML Model for IP Analyses - Part 1
# Data Collection

# Importing Libraries
# Importing ML building libries and tools from Python
import pandas as pd
import numpy as np

# Importing tarfile modele for opening DGArchive tar file
import tarfile
# Importing os module to writing/reading files to the os
import os
# Importing glob module for merging several files into one
import glob

# Root Directory
root_path = "D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Jupyter"

# Models / Algorithms To Be Examined:
    # 1. Logistic Regression
    # 2. K-Nearest Neighbour
    # 3. Random Forest

# Creating Bad CSV (Malicious URLs)

In [17]:
# Importing DGArchive Data
# print(str(os.getcwd()))
print('Starting DGA Import')

dga_files_path = "D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full"
files = glob.glob(os.path.join(dga_files_path, '**', "*.csv"), recursive=True)

# Empty list for storing multiple dataframes
data_frame_list = []

print(f'Files size: {len(files)}')
i=1
for file in files:
    try:
        # Getting File Name
        group = os.path.basename(file)
        print(f'Adding file {i} {file}')
        i+=1
        # Reading CSV's
        temp_data_frame = pd.read_csv(file, usecols=['domain'], low_memory=False, on_bad_lines='skip')
        # Adding New Column for File Name
        temp_data_frame['Group'] = group
        # Cleaning the Added Column
        # Removing .csv
        temp_data_frame['Group'] = temp_data_frame['Group'].replace('.csv', '', regex=False)
        # Appending to temp list
        data_frame_list.append(temp_data_frame)
    except Exception as e:
        print(f'Cannot find file {file}')
        print(e)
    
# Checking the size of list
print(f'Data Frame lenght: {len(data_frame_list)}')
try:
    dga_data_frame = pd.concat(data_frame_list, axis=0)
    if not os.path.isdir('imported_data'):
        print('Creating a Directory')
        os.mkdir('imported_data')
    dga_path = "imported_data/dga.csv"
    dga_data_frame.to_csv(dga_path, index=False)
    print(f'Saved Data to new file path: {dga_path}')
except ValueError:
    print('Data frame is empty')

Starting DGA Import
Files size: 127
Adding file 1 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\abcbot_dga.csv
Adding file 2 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\alien_dga.csv
Adding file 3 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\amadey_dga.csv
Adding file 4 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\ares_dga.csv
Adding file 5 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\bamital_dga.csv
Adding file 6 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\banjori_dga.csv
Adding file 7 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\bazarbackdoor_dga.csv
Adding file 8 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\bedep_dga.csv
Adding file 9 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\bigviktor_dga.csv
Adding file 10 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\blackhole_dga.csv
Adding file 11 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\bobax_dga.csv
Adding file 12 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\bumblebee_dga.csv
Adding file 13 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\calfbot_dga.csv
Adding file 14 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\ccleaner_dga.csv
Adding file 15 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\chaes_dga.csv
Adding file 16 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\chinad_dga.csv
Adding file 17 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\chir_dga.csv
Adding file 18 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\conficker_dga.csv
Adding file 19 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\copperstealer_dga.csv
Adding file 20 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\corebot_dga.csv
Adding file 21 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\cryptolocker_dga.csv
Adding file 22 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\darkcracks_dga.csv
Adding file 23 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\darkshell_dga.csv
Adding file 24 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\darkwatchman_dga.csv
Adding file 25 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\diamondfox_dga.csv
Adding file 26 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\dircrypt_dga.csv
Adding file 27 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\dmsniff_dga.csv
Adding file 28 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\dnsbenchmark_dga.csv
Adding file 29 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\dnschanger_dga.csv
Adding file 30 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\downloader_dga.csv
Adding file 31 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\dyre_dga.csv
Adding file 32 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\ebury_dga.csv
Adding file 33 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\ekforward_dga.csv
Adding file 34 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\emotet_dga.csv
Adding file 35 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\enviserv_dga.csv
Adding file 36 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\feodo_dga.csv
Adding file 37 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\flashback_dga.csv
Adding file 38 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\flubot_dga.csv
Adding file 39 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\fobber_dga.csv
Adding file 40 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\g01_dga.csv
Adding file 41 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\gameover_dga.csv
Adding file 42 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\gameover_p2p.csv
Adding file 43 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\gazavat_dga.csv
Adding file 44 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\gozi_dga.csv
Adding file 45 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\goznym_dga.csv
Adding file 46 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\grandoreiro_dga.csv
Adding file 47 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\gspy_dga.csv
Adding file 48 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\hesperbot_dga.csv
Adding file 49 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\infy_dga.csv
Adding file 50 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\kfos_dga.csv
Adding file 51 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\kingminer_dga.csv
Adding file 52 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\lechiket_dga.csv
Adding file 53 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\locky_dga.csv
Adding file 54 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\m0yvtdd_dga.csv
Adding file 55 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\m0yv_dga.csv
Adding file 56 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\madmax_dga.csv
Adding file 57 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\makloader_dga.csv
Adding file 58 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\matsnu_dga.csv
Adding file 59 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\metastealer_dga.csv
Adding file 60 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\mirainomi_dga.csv
Adding file 61 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\mirai_dga.csv
Adding file 62 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\misfox_dga.csv
Adding file 63 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\monerominer_dga.csv
Adding file 64 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\murofetweekly_dga.csv
Adding file 65 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\murofet_dga.csv
Adding file 66 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\mydoomtid_dga.csv
Adding file 67 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\mydoom_dga.csv
Adding file 68 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\n3cr0m0rph_dga.csv
Adding file 69 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\necurs_dga.csv
Adding file 70 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\ngioweb_dga.csv
Adding file 71 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\nymaim2_dga.csv
Adding file 72 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\nymaim_dga.csv
Adding file 73 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\oderoor_dga.csv
Adding file 74 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\omexo_dga.csv
Adding file 75 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\orchardgenesis_dga.csv
Adding file 76 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\orchard_dga.csv
Adding file 77 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\padcrypt_dga.csv
Adding file 78 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\pandabanker_dga.csv
Adding file 79 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\phorpiex_dga.csv
Adding file 80 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\pitou_dga.csv
Adding file 81 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\prometei_dga.csv
Adding file 82 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\proslikefan_dga.csv
Adding file 83 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\pseudomanuscrypt_dga.csv
Adding file 84 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\pushdotid_dga.csv
Adding file 85 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\pushdo_dga.csv
Adding file 86 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\pykspa2s_dga.csv
Adding file 87 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\pykspa2_dga.csv
Adding file 88 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\pykspa_dga.csv
Adding file 89 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\qadars_dga.csv
Adding file 90 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\qakbot_dga.csv
Adding file 91 D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/DGArchive/dgarchive_full\qhost_dga.csv

In [18]:
dga_data_frame.head()

                domain           Group
0        aabebtdpa.com  abcbot_dga.csv
1  aabebtdpa.pages.dev  abcbot_dga.csv
2         aabebtdpa.tk  abcbot_dga.csv
3        aabtpadeb.com  abcbot_dga.csv
4  aabtpadeb.pages.dev  abcbot_dga.csv

In [29]:
os.chdir("D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/URLhaus")
print(f'Current Directory: {os.getcwd()}')
# data_frame = pd.read_csv('csv.txt')
data_frame_skipped = pd.read_csv('csv.txt',skiprows=9)
# data_frame.head(2);
data_frame_skipped

Current Directory: D:\Users\Nyk\NCI\OneDrive - National College of Ireland\NCI\Year 4\3 Final Year Project\S3\0. Deliverables\Final Submission (AUG 3)\2. Code\ML Building\Datasets\URLhaus

,3851096,2026-05-21 00:17:07,https://orbital-velocity.fit/98a1df5c-d42b-4208-b5c1-ab4d41d96217/zone.id,online,2026-05-21 00:17:07.1,malware_download,ClearFake,https://urlhaus.abuse.ch/url/3851096/,anonymous
0,3851095,2026-05-21 00:15:13,http://182.126.118.95:55238/i,online,2026-05-21 00:15:13,malware_download,"32-bit,elf,mips,Mozi",https://urlhaus.abuse.ch/url/3851095/,geenensp
1,3851094,2026-05-21 00:13:19,http://115.53.56.76:36157/bin.sh,online,2026-05-21 00:13:19,malware_download,"32-bit,elf,mips,Mozi",https://urlhaus.abuse.ch/url/3851094/,geenensp
2,3851093,2026-05-21 00:12:17,http://182.126.118.14:44797/bin.sh,online,2026-05-21 00:12:17,malware_download,"32-bit,elf,mips,Mozi",https://urlhaus.abuse.ch/url/3851093/,geenensp
3,3851092,2026-05-21 00:02:16,http://110.36.74.148:49905/i,online,2026-05-21 00:02:16,malware_download,"32-bit,elf,mips,Mozi",https://urlhaus.abuse.ch/url/3851092/,geenensp
4,3851091,2026-05-21 00:00:21,http://42.227.42.49:42416/bin.sh,online,2026-05-21 00:00:21,malware_download,"32-bit,elf,mips,Mozi",https://urlhaus.abuse.ch/url/3851091/,geenensp
...,...,...,...,...,...,...,...,...,...
78271,34267,2018-07-18 23:49:03,http://xn--90abegbttpjb3bzb2j.xn--p1ai/doc/En/...,online,2026-05-20 18:36:04,malware_download,"doc,emotet,epoch2,heodo",https://urlhaus.abuse.ch/url/34267/,Cryptolaemus1
78272,34227,2018-07-18 22:51:45,http://xn--90abegbttpjb3bzb2j.xn--p1ai/Notific...,online,2026-05-20 21:18:57,malware_download,"doc,emotet,epoch1,heodo",https://urlhaus.abuse.ch/url/34227/,Cryptolaemus1
78273,34102,2018-07-18 18:44:03,http://xn--90abegbttpjb3bzb2j.xn--p1ai/doc/En/...,online,2026-05-20 18:50:43,malware_download,"doc,emotet,heodo",https://urlhaus.abuse.ch/url/34102/,anonymous
78274,16630,2018-06-07 18:40:03,http://robertrowe.com/DOC/Past-Due-invoice/,online,2026-05-20 20:19:53,malware_download,"doc,emotet,epoch1,heodo",https://urlhaus.abuse.ch/url/16630/,Cryptolaemus1
78275,15711,2018-06-05 22:09:14,http://robertrowe.com/STATUS/Auditor-of-State-...,online,2026-05-20 19:54:56,malware_download,"doc,emotet,heodo",https://urlhaus.abuse.ch/url/15711/,Cryptolaemus1

In [13]:
# Importing URLhaus data
print('Starting URLhaus Import')

# Extracting ZIP File
from zipfile import ZipFile

zip_path = "D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/URLhaus"
try:
    print('Extracting files from zip object')
    with ZipFile(zip_path + '/full.csv.zip', 'r') as z_object:
        z_object.extractall(path=zip_path)
except:
    print('Unable to extract files from zip')

# Checking if there are files
if os.listdir(zip_path) == []:
    print("No files found in the directory.")
else:
    # Getting information on what files are there
    os.chdir(zip_path)
    files = os.listdir()
    for file in files:
        print(f'File: {file}')
    try: 
        if os.path.isfile('csv.txt'):
            print('Reading CSV')
            print('Changing Directory')
            data_frame = pd.read_csv('csv.txt',skiprows=9)
            os.chdir(root_path)
            if not os.path.isdir('imported_data'):
                print('Making path')
                os.mkdir('imported_data')
            url_path = "imported_data/url.csv"
            data_frame.to_csv(url_path, index=False)
            print(f'Saved Data to: {root_path + url_path}')
        else:
            print('csv.txt Not found')
    except Exception as e:
        print('Data frame is empty')
        print(f'Exception: {e}')

Starting URLhaus Import
Extracting files from zip object
File: csv.txt
File: full.csv.zip
File: url.csv
Reading CSV
Changing Directory
Saved Data to: D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Jupyterimported_data/url.csv

In [11]:
# Importing Kaggle Data
kaggle_path = 'D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/Kaggle'

# Importing Phishing Dataset

print('Getting Phishing Dataset (Kaggle)')
try:
    os.chdir(kaggle_path)
    
    print('Reading Phishing CSV')
    if os.path.isfile('phishing_site_urls.csv'):
        phish_data_frame = pd.read_csv('phishing_site_urls.csv')
        os.chdir(root_path)
        phish_path = ''
        if not os.path.isdir('imported_data'):
            print('Making directory')
            os.mkdir('imported_data')
        phish_path = "/imported_data/phish.csv"
        phish_data_frame.to_csv(root_path + phish_path, index=False)
        print(f'Saved Phishing Dataset to: {root_path + phish_path}')
    else:
        print('File phishing_site_urls.csv not found!')
except Exception as e:
    print('An error/exception occured.')
    print(f'Exception: {e}')

Getting Phishing Dataset (Kaggle)
Reading Phishing CSV
Saved Phishing Dataset to: D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Jupyter/imported_data/phish.csv

In [15]:
# Importing Kaggle Data
kaggle_path = 'D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/Kaggle'

# Importing Bad URL's Dataset

print("Getting Bad URL's Dataset (Kaggle)")
try:
    os.chdir(kaggle_path)
    
    print('Reading Bad URL CSV')
    if os.path.isfile('merged_urls_dataset.csv'):
        bad_url_data_frame = pd.read_csv('merged_urls_dataset.csv')
        os.chdir(root_path)
        if not os.path.isdir('imported_data'):
            print('Making directory')
            os.mkdir('imported_data')
        bad_url_path = "/imported_data/bad_url.csv"
        bad_url_data_frame.to_csv(root_path + bad_url_path, index=False)
        print(f'Saved Phishing Dataset to: {root_path + bad_url_path}')
    else:
        print('File merged_urls_dataset.csv not found!')
except Exception as e:
    print('An error/exception occured.')
    print(f'Exception: {e}')

Getting Bad URL's Dataset (Kaggle)
Reading Bad URL CSV
Saved Phishing Dataset to: D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Jupyter/imported_data/bad_url.csv

# Creating Good CSV (URL of Legitimate / Benign

In [2]:
good_csv_path = 'D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Datasets/Good_CSV'
# Importing ood URL Dataset

### Majestic

In [96]:
# Importing Majestic Million Top 1 Million Visited Domains
os.chdir(good_csv_path)
mm_data = pd.read_csv('majestic_million.csv')
mm_data.head()

,GlobalRank,TldRank,Domain,TLD,RefSubNets,RefIPs,IDN_Domain,IDN_TLD,PrevGlobalRank,PrevTldRank,PrevRefSubNets,PrevRefIPs
0,1,1,google.com,com,507545,2239575,google.com,com,1,1,505423,2235784
1,2,2,facebook.com,com,481747,2257665,facebook.com,com,2,2,479096,2251864
2,3,3,youtube.com,com,435146,1869495,youtube.com,com,3,3,433311,1866475
3,4,4,instagram.com,com,400297,1770925,instagram.com,com,4,4,398226,1766778
4,5,5,twitter.com,com,379376,1509544,twitter.com,com,5,5,377661,1507746

In [97]:
# Removing Irrelevant Columns
mm_data = mm_data.drop(columns=['GlobalRank', 'TldRank', 'TLD', 'RefSubNets', 'RefIPs', 'IDN_Domain', 'IDN_TLD', 'PrevGlobalRank', 'PrevTldRank', 'PrevRefSubNets', 'PrevRefIPs'])
mm_data.head()

          Domain
0     google.com
1   facebook.com
2    youtube.com
3  instagram.com
4    twitter.com

In [16]:
# Creating a URL Column Function
def url_column(data_frame):
    try:
        print('Converting Domain Names to URL address')
        has_protocol = data_frame['Domain'].str.startswith(
            ('http://','https://')
        )
        has_www = data_frame['Domain'].str.startswith(
            ('www.', 'http://www.', 'https://www.')
        )

        if has_protocol.any():
            print('Protocol Found')
        else:
            print('Protocol Not Found')
            
        data_frame['URL'] = data_frame['Domain']
        data_frame.loc[~has_protocol, 'URL'] = ('https://' + data_frame.loc[~has_protocol, 'Domain'])
        data_frame.loc[~has_www, 'URL'] =(data_frame.loc[~has_www, 'URL'].str.replace('https://','https://www.',regex=False))
        print('Conversion Completed')
        return data_frame
    except Exception as e:
        print('Exception occured in url_column function')
        print(f'Exception: {e}')
        return None

In [99]:
# Converting Domain to URL
mm_data = url_column(mm_data)

Converting Domain Names to URL address
Protocol Not Found
Conversion Completed

In [100]:
# Checking Results
mm_data.head()

          Domain                        URL
0     google.com     https://www.google.com
1   facebook.com   https://www.facebook.com
2    youtube.com    https://www.youtube.com
3  instagram.com  https://www.instagram.com
4    twitter.com    https://www.twitter.com

### Cisco

In [14]:
# Importing CISCO's Top 1 Million Visited Domains
os.chdir(good_csv_path)
cisco_data = pd.read_csv('top-1m.csv',names=['ID', 'Domain'])
cisco_data.head()

   ID              Domain
0   1          google.com
1   2         gstatic.com
2   3      www.google.com
3   4       microsoft.com
4   5  data.microsoft.com

In [17]:
# Converting Domain to URL
cisco_data = url_column(cisco_data)

Converting Domain Names to URL address
Protocol Found
Conversion Completed

In [18]:
# Checking Results
cisco_data.head()

   ID              Domain                             URL
0   1          google.com          https://www.google.com
1   2         gstatic.com         https://www.gstatic.com
2   3      www.google.com          https://www.google.com
3   4       microsoft.com       https://www.microsoft.com
4   5  data.microsoft.com  https://www.data.microsoft.com

### Kaggle

In [3]:
# Importing First Kaggle File
os.chdir(good_csv_path)
kaggle_balanced = pd.read_csv('kaggle_balanced_urls.csv')
kaggle_balanced.head()

                         url   label  result
0     https://www.google.com  benign       0
1    https://www.youtube.com  benign       0
2   https://www.facebook.com  benign       0
3      https://www.baidu.com  benign       0
4  https://www.wikipedia.org  benign       0

In [5]:
# remove non-benign labels
label_items = kaggle_balanced['label'].unique()
print('Items in Label column:')
print(label_items)

Items in Label column:
['benign' 'malicious']

In [9]:
# remove unnecessary columns
item = kaggle_balanced[((kaggle_balanced.label == 'malicious'))].index
kaggle_balanced = kaggle_balanced.drop(item)
new_label_items = kaggle_balanced['label'].unique()
print(new_label_items)

['benign']

In [10]:
kaggle_balanced = kaggle_balanced.drop(columns=['label', 'result'])
kaggle_balanced.head()

                         url
0     https://www.google.com
1    https://www.youtube.com
2   https://www.facebook.com
3      https://www.baidu.com
4  https://www.wikipedia.org

## Saving

In [12]:
### Saving good_csv function
def saving_good_csv(data_frame, name):
    try:
        print('Starting Saving')
        os.chdir(root_path)
        if name == 'Cisco':
            file_name = 'cisco.csv'
        elif name == 'Majestic':
            file_name = 'majestic.csv'
        elif name == 'Kaggle_Balanced':
            file_name = 'kaggle_balanced.csv'
        else:
            print('Name not recognised')
            return
             
        if not os.path.isdir('imported_data'):
            print('Making imported_data directory')
            os.mkdir('imported_data')
        os.chdir(root_path + '/imported_data')
        if not os.path.isdir('good_csv'):
            print('Making good_csv directory')
            os.mkdir('good_csv')
        os.chdir(root_path + '/imported_data/good_csv')
        data_frame.to_csv(root_path + '/imported_data/good_csv/' + file_name, index=False)
        print('Save Completed')
    except Exception as e:
        print('Exception occurred')
        print(f'Exception: {e}')

In [114]:
# Saving Good CSV's

##### Saving Majestic

In [115]:
saving_good_csv(mm_data, 'Majestic')

Starting Saving
Save Completed

##### Saving Cisco

In [19]:
saving_good_csv(cisco_data, 'Cisco')

Starting Saving
Save Completed

##### Saving Kaggle

In [20]:
saving_good_csv(kaggle_balanced, 'Kaggle_Balanced')

Starting Saving
Save Completed