In [3]:
# ML Model for IP Analyses - Part 4
# Creating Additional Informational Columns Based on the URL

# Importing Libraries for ML
import pandas as pd
from sklearn import linear_model
import numpy as np
import tldextract as tld

import os
import re

In [5]:
# Obtaining logistic Regression Model
logistic = linear_model.LogisticRegression()

In [6]:
# Getting the csv file
file_path = "D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Jupyter/imported_data/cleaned_csv/to_join/combined"
os.chdir(file_path)
os.listdir()

['balanced_combined.csv', 'combined.csv', 'combined.csv.gz']

In [7]:
data = pd.read_csv('balanced_combined.csv')
data.head()

,Unnamed: 0.1,Unnamed: 0,URL,Threat
0,0,7007930,https://www.repvtrhsrbpku.ug,1
1,1,953411,https://www.cbbridal.com,0
2,2,33840666,https://www.zrtvxqyqtslf.info,1
3,3,30479797,https://www.hrkyraongvqnaxfct.pw,1
4,4,354338,https://www.volcengine-cache-weboffice.wpscdn.cn,0

In [8]:
# Dropping Columns
data = data.drop(columns={'Unnamed: 0.1','Unnamed: 0'})
data.head()

                                                URL  Threat
0                      https://www.repvtrhsrbpku.ug       1
1                          https://www.cbbridal.com       0
2                     https://www.zrtvxqyqtslf.info       1
3                  https://www.hrkyraongvqnaxfct.pw       1
4  https://www.volcengine-cache-weboffice.wpscdn.cn       0

In [9]:
# Creating Extra Informational Columns
# Based on URL data

In [10]:
# Adding URL Length
data['Length'] = 0
for index in data.index:
    data.loc[index, 'Length'] = len(data.loc[index, 'URL'])

In [11]:
data.head()

                                                URL  Threat  Length
0                      https://www.repvtrhsrbpku.ug       1      28
1                          https://www.cbbridal.com       0      24
2                     https://www.zrtvxqyqtslf.info       1      29
3                  https://www.hrkyraongvqnaxfct.pw       1      32
4  https://www.volcengine-cache-weboffice.wpscdn.cn       0      48

In [12]:
# Adding https analyses
data['Contains_HTTPS'] = 0
for index in data.index:
    if 'https' in data.loc[index, 'URL']:
        data.loc[index, 'Contains_HTTPS'] = 1

In [13]:
data.head()

,URL,Threat,Length,Contains_HTTPS
0,https://www.repvtrhsrbpku.ug,1,28,1
1,https://www.cbbridal.com,0,24,1
2,https://www.zrtvxqyqtslf.info,1,29,1
3,https://www.hrkyraongvqnaxfct.pw,1,32,1
4,https://www.volcengine-cache-weboffice.wpscdn.cn,0,48,1

In [14]:
# IP address presence column
data['Has_IP'] = 0
pattern = r'(\d{1,3}\.){3}\d{1,3}'
data['Has_IP'] = data['URL'].str.extract(pattern).notna().astype(int)
data.head()

,URL,Threat,Length,Contains_HTTPS,Has_IP
0,https://www.repvtrhsrbpku.ug,1,28,1,0
1,https://www.cbbridal.com,0,24,1,0
2,https://www.zrtvxqyqtslf.info,1,29,1,0
3,https://www.hrkyraongvqnaxfct.pw,1,32,1,0
4,https://www.volcengine-cache-weboffice.wpscdn.cn,0,48,1,0

In [51]:
# Digit Counting
data['Digit_Count'] = 0
for index in data.index:
    count = 0
    for c in data.loc[index, 'URL']:
        if c.isdigit():
            count += 1
    if count > 0:
        data.loc[index, 'Digit_Count'] = count

In [16]:
data.head()

,URL,Threat,Length,Contains_HTTPS,Has_IP,Digit_Count
0,https://www.repvtrhsrbpku.ug,1,28,1,0,0
1,https://www.cbbridal.com,0,24,1,0,0
2,https://www.zrtvxqyqtslf.info,1,29,1,0,0
3,https://www.hrkyraongvqnaxfct.pw,1,32,1,0,0
4,https://www.volcengine-cache-weboffice.wpscdn.cn,0,48,1,0,0

In [50]:
data['Dot_Count'] = 0
for index in data.index:
    count_dots = 0
    string = data.loc[index, 'URL']
    count_dots = string.count('.')
    if count_dots > 0:
        data.loc[index, 'Dot_Count'] = count_dots
data.head()

,URL,Threat,Length,Contains_HTTPS,Has_IP,Digit_Count,Dot_Count,Has_Subdomain,Subdomain_Count,Hyphen_Count,Special_Count
0,https://www.repvtrhsrbpku.ug,1,28,1,0,0,2,0,0,0,1
1,https://www.cbbridal.com,0,24,1,0,0,2,0,0,0,1
2,https://www.zrtvxqyqtslf.info,1,29,1,0,0,2,0,0,0,1
3,https://www.hrkyraongvqnaxfct.pw,1,32,1,0,0,2,0,0,0,1
4,https://www.volcengine-cache-weboffice.wpscdn.cn,0,48,1,0,0,3,1,1,2,3

In [28]:
# Counting Sub-domains Present
data['Has_Subdomain'] = 0
data['Subdomain_Count'] = 0
for index in data.index:
    sections = tld.extract(data.loc[index, 'URL'])
    count = len(sections.subdomain.split('.'))
    if count > 1:
        data.loc[index, 'Has_Subdomain'] = 1
        data.loc[index, 'Subdomain_Count'] = (count-1)
data.head()

,URL,Threat,Length,Contains_HTTPS,Has_IP,Digit_Count,Dot_Count,Has_Subdomain,Subdomain_Count
0,https://www.repvtrhsrbpku.ug,1,28,1,0,0,2,0,0
1,https://www.cbbridal.com,0,24,1,0,0,2,0,0
2,https://www.zrtvxqyqtslf.info,1,29,1,0,0,2,0,0
3,https://www.hrkyraongvqnaxfct.pw,1,32,1,0,0,2,0,0
4,https://www.volcengine-cache-weboffice.wpscdn.cn,0,48,1,0,0,3,1,1

In [33]:
# Counting Hashes in URL
data['Hyphen_Count'] = 0
for index in data.index:
    data.loc[index, 'Hyphen_Count'] = data.loc[index, 'URL'].count('-')

In [34]:
data.head()

,URL,Threat,Length,Contains_HTTPS,Has_IP,Digit_Count,Dot_Count,Has_Subdomain,Subdomain_Count,Hyphen_Count
0,https://www.repvtrhsrbpku.ug,1,28,1,0,0,2,0,0,0
1,https://www.cbbridal.com,0,24,1,0,0,2,0,0,0
2,https://www.zrtvxqyqtslf.info,1,29,1,0,0,2,0,0,0
3,https://www.hrkyraongvqnaxfct.pw,1,32,1,0,0,2,0,0,0
4,https://www.volcengine-cache-weboffice.wpscdn.cn,0,48,1,0,0,3,1,1,2

In [49]:
# Creating Column for Counting Other Special Characters
data['Special_Count'] = 0
for index in data.index:
    count = 0
    for c in data.loc[index, 'URL']:
        if not c.isalnum():
            if c != '.' and c != '/':
                count += 1
                data.loc[index, 'Special_Count'] = count
data.head()

,URL,Threat,Length,Contains_HTTPS,Has_IP,Digit_Count,Dot_Count,Has_Subdomain,Subdomain_Count,Hyphen_Count,Special_Count
0,https://www.repvtrhsrbpku.ug,1,28,1,0,0,2,0,0,0,1
1,https://www.cbbridal.com,0,24,1,0,0,2,0,0,0,1
2,https://www.zrtvxqyqtslf.info,1,29,1,0,0,2,0,0,0,1
3,https://www.hrkyraongvqnaxfct.pw,1,32,1,0,0,2,0,0,0,1
4,https://www.volcengine-cache-weboffice.wpscdn.cn,0,48,1,0,0,3,1,1,2,3

In [ ]:
### Adding Typosquating

In [54]:
# Saving the Edited Data Frame to new File
structured_path = "D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Jupyter/imported_data/structured_data"
data.to_csv(structured_path + '/structured_data.csv')